### ISSUE TITLE
Consider splitting into multiple packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/chaiscript#1]
I saw this new package being worked on and noticed that it provides both library and executable. For such cases it's a good idea to split it into separate library and executable packages. In particular, without this, you won't be able to have run-time dependency on the library and build-time dependency on the executable. I would suggest the following package names:

```
libchaiscript
chaiscript
```

Per: https://github.com/build2/HOWTO/blob/master/entries/name-packages-in-project.md

Also, if the tests/examples use both the library and executable, then they would also need to be separate packages (but if they only need the library, then they can be part of the library as per usual). But I see you have already made them separate packages, though the names are probably too generic (I would suggest `libchaiscript-{tests,samples}`).

For an example of a project that uses this approach, see: https://git.codesynthesis.com/cgit/xsd/xsd/tree/

Also  this HOWTO is likely relevant: https://github.com/build2/HOWTO/blob/master/entries/handle-tests-with-extra-dependencies.md

**Comment by lyrahgames** [comment]
That was fast. Yes, it was only my initial attempt yesterday evening. Earlier this day, I haven't received any notification for this issue and started changing the layout in a different way. But I will then also separate the library and the executable.

Concerning the naming, the executable for the library `chaiscript` is called `chai`. So, I thought those names might be good. Would you rather like to use the `lib` prefix for `chaiscript`?

```
libchaiscript
chai
```

**Comment by Klaim** [comment]
(Thanks @lyrahgames for working on this, I actually had an old attempt several years ago but hit too many issues and halted my efforts. I'll try to help when I can. 👍🏽 )

**Comment by boris-kolpackov** [comment]
I would keep the executable package name `chaiscript`. There is, for example, already a Debian package called `chai`: https://packages.debian.org/bullseye/chai

And, yes, the library would then be `libchaiscript`.

**Comment by lyrahgames** [comment]
Perfect. Thank you. Already rewrote this yesterday evening.
