### ISSUE TITLE
MinGW linker hangs when linking the test 

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/chaiscript#2]
I've noticed our CI machines timed out on the MinGW configuration. Looking inside I see it's stuck trying to link `tests\tests.exe`. I let it run for a few more hours but it's still linking. So whatever chaiscript does, it seem to expose some pathology in MinGW `ld` and I think we should exclude these configurations from the build.

**Comment by lyrahgames** [comment]
Yes, it was one of my last tests yesterday. In the `CMakeLists.txt` file of ChaiScript, it was mentioned that using MinGW will result in long compile times when not providing the `-O3` option. I would not have assumed it to be that long. Based on this, it would be good to try it again with the optimizer option enabled, I think.

**Comment by boris-kolpackov** [comment]
Yes, the two suspected ones were non-optimized: https://ci.stage.build2.org/?builds=libchaiscript&tc=windows_10-gcc_**

You can try to exclude that and keep the `O2` and `static_O2` ones.

**Comment by lyrahgames** [comment]
I have been experimenting and tried to add them but it seems that my restrictions did not work. So, you should probably kill the unoptimized MinGW jobs, again. Sorry about that.

**Comment by lyrahgames** [comment]
I have tried to use the following restrictions on the library. But then MinGW on Windows does not seem to run at all. I am not sure why. You know what I am doing wrong?

```
builds: all
builds: -( +windows &gcc &!optimized )
```

**Comment by boris-kolpackov** [comment]
Hm, don't see anything wrong with the expression and it seems to work for me:

```
git clone -b 1.0 https://git.build2.org/hello/libhello.git
cd libhello/
bdep init -C @gcc cc
bdep ci --builds 'all' --builds '-( +windows &gcc &!optimized )'
```

https://ci.stage.build2.org/@d3c4e567-e53c-4509-9327-aab700fbacf0?builds=&pv=&th=*&tg=&tc=windows_10-gcc_**&pc=&rs=*
